apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: jet-aks
  labels:
    crossplane.io/xrd: xmanagedclusters.compositions.io
    provider: jet
    cluster: aks
spec:
  compositeTypeRef:
    apiVersion: compositions.io/v1alpha1
    kind: XManagedCluster
  writeConnectionSecretsToNamespace: crossplane-system 
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  - name: region
    patches:
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.location
      transforms:
      - type: map
        map:
          use1: eastus
          use2: eastus2
          usw1: westus
          usw2: westus2
          cac: canadacentral
          sae: brazilsouth
          afs: southafricanorth
          euc: germanywestcentral
          euw1: northeurope
          euw2: uksouth
          euw3: francecentral
          eus: switzerlandnorth
          eun: swedencentral
          ape: eastasia
          aps1: westindia
          apne1: japaneast
          apne2: koreacentral
          apne3: japanwest
          apse1: southeastasia
          apse2: australiaeast
          apse3: australiacentral 
  resources:
  - name: resourcegroup
    base:
      apiVersion: azure.jet.crossplane.io/v1alpha2
      kind: ResourceGroup
      spec:
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - type: PatchSet
      patchSetName: region
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "rg-%s"
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.labels.resourcegroup
  - name: vnet  
    base:
      apiVersion: network.azure.jet.crossplane.io/v1alpha2
      kind: VirtualNetwork 
      spec:
        forProvider:
          resourceGroupNameSelector: 
            matchControllerRef: true
          addressSpace:
          - 10.244.32.0/19        
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - type: PatchSet
      patchSetName: region
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "vnet-%s"
  - name: subnet 
    base:
      apiVersion: network.azure.jet.crossplane.io/v1alpha2
      kind: Subnet 
      spec:
        forProvider:
          resourceGroupNameSelector: 
            matchControllerRef: true
          virtualNetworkNameSelector:
            matchControllerRef: true 
          addressPrefixes: 
          - "10.244.32.0/22"
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "snet-%s"
  - name: akscluster
    base:
      apiVersion: containerservice.azure.jet.crossplane.io/v1alpha2
      kind: KubernetesCluster
      spec:
        forProvider:
          dnsPrefix: xpjet
          roleBasedAccessControl:
          - enabled: true
          resourceGroupNameSelector: 
            matchControllerRef: true
          defaultNodePool:
          - name: default
            nodeCount: 1
            vmSize: Standard_D2s_v3 
            vnetSubnetIDSelector:
              matchControllerRef: true
          identity:
          - type: "SystemAssigned"     
        writeConnectionSecretToRef:
          namespace: crossplane-system 
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - type: PatchSet
      patchSetName: region
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.id
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-akscluster"
    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.forProvider.kubernetesVersion
    # - fromFieldPath: spec.id
    #   toFieldPath: spec.forProvider.defaultNodePool[0].name      
    # - fromFieldPath: spec.parameters.nodeCount
    #   toFieldPath: spec.forProvider.defaultNodePool[0].nodeCount
    # - fromFieldPath: spec.parameters.nodeSize
    #   toFieldPath: spec.forProvider.defaultNodePool[0].vmSize
    #   transforms:
    #   - type: map
    #     map:
    #       small: Standard_D2s_v3
    #       medium: Standard_D4s_v3
    #       large: Standard_D8s_v3
    - fromFieldPath: spec.writeConnectionSecretToRef.namespace
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: status.clusterName
    - type: ToCompositeFieldPath
      fromFieldPath: status.conditions[0].status
      toFieldPath: status.controlPlaneStatus
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: status.fargateProfileStatus
      transforms:
      - type: string
        string:
          fmt: "NA4-%s" 
    connectionDetails:
    - fromConnectionSecretKey: kubeconfig
    readinessChecks:
    - type: MatchString
      fieldPath: status.conditions[0].status
      matchString: "True"
  - name: aksnode
    base:
      apiVersion: containerservice.azure.jet.crossplane.io/v1alpha2
      kind: KubernetesClusterNodePool
      spec:
        forProvider:
          kubernetesClusterIdSelector:
            matchControllerRef: true
          vnetSubnetIDSelector:
            matchControllerRef: true 
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.parameters.nodeCount
      toFieldPath: spec.forProvider.nodeCount
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.forProvider.vmSize
      transforms:
      - type: map
        map:
          small: Standard_D2s_v3
          medium: Standard_D4s_v3
          large: Standard_D8s_v3
    - type: ToCompositeFieldPath
      fromFieldPath: status.conditions[0].status
      toFieldPath: status.nodePoolStatus
    readinessChecks:
    - type: MatchString
      fieldPath: status.conditions[0].status
      matchString: "True"

  - name: helm
    base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: ProviderConfig
        spec:
          credentials:
            source: Secret
            secretRef:
              key: kubeconfig
    patches:
      - fromFieldPath: spec.id
        toFieldPath: metadata.name
      - fromFieldPath: spec.writeConnectionSecretToRef.namespace
        toFieldPath: spec.credentials.secretRef.namespace
      - fromFieldPath: spec.id
        toFieldPath: spec.credentials.secretRef.name
        transforms:
          - type: string
            string:
              fmt: "%s-akscluster"
    readinessChecks:
      - type: None
  - name: helm-crossplane
    base:
        apiVersion: helm.crossplane.io/v1beta1
        kind: Release
        spec:
          rollbackLimit: 3
          forProvider:
            namespace: crossplane-system
            chart:
              name: crossplane
              repository: https://charts.crossplane.io/stable
              version: "1.7.0"
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-crossplane"
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
  - name: kubernetes
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: ProviderConfig
      spec:
        credentials:
          source: Secret
          secretRef:
            key: kubeconfig
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.writeConnectionSecretToRef.namespace
      toFieldPath: spec.credentials.secretRef.namespace
    - fromFieldPath: spec.id
      toFieldPath: spec.credentials.secretRef.name
      transforms:
        - type: string
          string:
            fmt: "%s-akscluster"
    readinessChecks:
      - type: None
  - name: k8s-ns-prod
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Namespace
            metadata:
              name: production
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
        - type: string
          string:
            fmt: "%s-ns-prod"
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
