apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: xpeks2
  namespace: managed
  labels:
    owner: andrzej
spec:
  id: xpeks2
  compositionSelector:
    matchLabels:
      cluster: eks
  parameters:
    version: "1.21" 
    fargateNamespace: default
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3 
    # region: euc
    # region: apne2 
    region: cac
  writeConnectionSecretToRef:
    name: xpeks2