apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: xpeks
  namespace: managed
  labels:
    owner: andrzej
spec:
  id: xpeks
  compositionSelector:
    matchLabels:
      cluster: eks
  parameters:
    version: "1.21" 
    fargateNamespace: default
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3 
    # region:  apne2
    # region: usw1
    region: euc
  writeConnectionSecretToRef:
    name: xpeks