apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: xpjetgke
  namespace: managed
  labels:
    owner: andrzej
spec:
  id: xpjetgke
  compositionSelector:
    matchLabels:
      cluster: gke
      provider: jet
  parameters:
    version: "latest"
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3
    # region:  use1, eus
    region: euc
  writeConnectionSecretToRef:
    name: xpjetgke