apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: xpjeteks
  namespace: managed
  labels:
    owner: andrzej
spec:
  id: xpjeteks
  compositionSelector:
    matchLabels:
      cluster: eks
      provider: jet
  parameters:
    version: "1.22"
    fargateNamespace: default
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3
    # region:  apne2
    # region: usw1
    region: euw1
  writeConnectionSecretToRef:
    name: xpjeteks
