---
apiVersion: azure.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: azure-jet-provider
spec:
  credentials:
    source: Secret
    secretRef: 
      namespace: ${PROVIDER_SECRET_NAMESPACE}
      name: azure-account-creds
      key: credentials