---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws-provider
spec:
  package: registry.upbound.io/crossplane/provider-aws:v0.23.0 
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: azure-provider
spec:
  package: registry.upbound.io/crossplane/provider-azure:v0.18.1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: gcp-provider
spec:
  package: registry.upbound.io/crossplane/provider-gcp:v0.19.0