---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws-provider
spec:
  package: crossplane/provider-aws:v0.29.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: azure-provider
spec:
  package: crossplane/provider-azure:v0.19.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: gcp-provider
spec:
  package: crossplane/provider-gcp:v0.21.0
