---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: aws-provider
spec:
  package: crossplane/provider-aws:v0.24.1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: azure-provider
spec:
  package: crossplane/provider-azure:v0.18.1
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: gcp-provider
spec:
  package: crossplane/provider-gcp:v0.20.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: helm-provider
spec:
  package: crossplane/provider-helm:v0.9.0 
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: kubernetes-provider
spec:
  package: crossplane/provider-kubernetes:v0.2.0