apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aks
  labels:
    crossplane.io/xrd: xmanagedclusters.compositions.io
    provider: azure
    cluster: aks
spec:
  compositeTypeRef:
    apiVersion: compositions.io/v1alpha1
    kind: XManagedCluster
  writeConnectionSecretsToNamespace: upbound-system  
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - name: resourcegroup
    base:
      apiVersion: azure.jet.crossplane.io/v1alpha2
      kind: ResourceGroup
      spec:
        forProvider:
          location: westus2
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "rg-%s"
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.labels.resourcegroup
  - name: vnet  
    base:
      apiVersion: network.azure.jet.crossplane.io/v1alpha2
      kind: VirtualNetwork 
      spec:
        forProvider:
          location: westus2
          resourceGroupNameSelector: 
            matchControllerRef: true
          addressSpace:
          - 10.244.32.0/19        
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "vnet-%s"
  - name: subnet 
    base:
      apiVersion: network.azure.jet.crossplane.io/v1alpha2
      kind: Subnet 
      spec:
        forProvider:
          location: westus2
          resourceGroupNameSelector: 
            matchControllerRef: true
          virtualNetworkNameSelector:
            matchControllerRef: true 
          addressPrefixes: 
          - 10.244.32.0/22
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "snet-%s"
  - name: aks
    base:
      apiVersion: containerservice.azure.jet.crossplane.io/v1alpha2
      kind: KubernetesCluster
      spec:
        forProvider: # change patches 
          location: westus2 
          dnsPrefix: uxpaks
          defaultNodePool: # check patches and matchcontroller
          - name: default
            nodeCount: 1
            vmSize: "Standard_D2_v2"
          identity: # check identity
          - type: "SystemAssigned"        
          resourceGroupNameSelector: 
            matchControllerRef: true
          vnetSubnetIDSelector:
            matchControllerRef: true  
        writeConnectionSecretToRef:
          namespace: upbound-system 
        providerConfigRef:
          name: azure-jet-provider
    patches:
    - type: PatchSet
      patchSetName: metadata
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: status.clusterName       
    - fromFieldPath: spec.parameters.version
      toFieldPath: spec.version
    - fromFieldPath: spec.parameters.nodeCount
      toFieldPath: spec.nodeCount
    - fromFieldPath: spec.parameters.nodeSize
      toFieldPath: spec.nodeVMSize
      transforms:
      - type: map
        map:
          small: Standard_D2s_v3
          medium: Standard_D4s_v3
          large: Standard_D8s_v3
    - fromFieldPath: metadata.uid
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-akscluster"
    - fromFieldPath: spec.writeConnectionSecretToRef.namespace
    - type: ToCompositeFieldPath
      fromFieldPath: status.state
      toFieldPath: status.controlPlaneStatus
    - type: ToCompositeFieldPath
      fromFieldPath: status.state
      toFieldPath: status.nodePoolStatus
    - type: ToCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: status.fargateProfileStatus
      transforms:
      - type: string
        string:
          fmt: "NA4-%s" 
    connectionDetails:
    - fromConnectionSecretKey: kubeconfig
    readinessChecks:
    - type: MatchString
      fieldPath: "status.state"
      matchString: "Succeeded"
  - name: aks-nodes
    base:
      apiVersion: containerservice.azure.jet.crossplane.io/v1alpha2
      kind: KubernetesClusterNodePool
      spec:
        forProvider:
        location: westus2
        resourceGroupNameSelector: 
          matchControllerRef: true
        properties:
          addressSpace:
            addressPrefixes:
            - 10.244.32.0/19        
        providerConfigRef:
          name: azure-jet-provider
    patches: