apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: xpaks
  namespace: managed
  labels:
    owner: andrzej
spec:
  id: xpaks
  compositionSelector:
    matchLabels:
      cluster: aks
      provider: classic
  parameters:
    version: "1.22.11"
    # nodeSize: small
    # nodeCount: 3
    # region:  use1
    # region: eus
    region: euw1
  writeConnectionSecretToRef:
    name: xpaks
