apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: xpaks
  namespace: managed
  labels:
    owner: natzka
spec:
  id: xpaks
  compositionSelector:
    matchLabels:
      cluster: aks
      provider: native
  parameters:
    version: "1.23.12"
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3
    # region:  use1, eus, euc
    region: euw1
  writeConnectionSecretToRef:
    name: xpaks
