apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: xpeks
  namespace: managed
  labels:
    owner: natzka
spec:
  id: xpeks
  compositionSelector:
    matchLabels:
      cluster: eks
      provider: native
  parameters:
    version: "1.23"
    fargateNamespace: default
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3
    region: euw1
  writeConnectionSecretToRef:
    name: xpeks
