apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: xpgke
  namespace: managed
  labels:
    owner: natzka
spec:
  id: xpgke
  compositionSelector:
    matchLabels:
      cluster: gke
      provider: native
  parameters:
    version: "1.23"
    # version: "latest"
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3
    # region:  use1, euc
    region: euw2
  writeConnectionSecretToRef:
    name: xpgke
