apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: uxpeks
  namespace: managed
  labels:
    owner: natzka
spec:
  id: uxpeks
  compositionSelector:
    matchLabels:
      cluster: eks
      provider: official
  parameters:
    version: "1.21"
    fargateNamespace: default
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3
    # region:  use1, eus, euc
    region: euw1
  writeConnectionSecretToRef:
    name: uxpeks
