apiVersion: compositions.io/v1alpha1
kind: ManagedCluster
metadata:
  name: uxpgke
  namespace: managed
  labels:
    owner: andrzej
spec:
  id: uxpgke
  compositionSelector:
    matchLabels:
      cluster: gke
      provider: official
  parameters:
    version: "latest"
    # nodeSize: small ### Supported values: small, medium, large
    # nodeCount: 3
    # region:  use1, eus, euc
    region: euw2
  writeConnectionSecretToRef:
    name: uxpgke
